services:
  zulu:
    build: .
    container_name: zulu
    # image: ghcr.io/skorotkiewicz/zulu
    ports:
      - "8765:8765"
    environment:
      PORT: "8765"
    volumes:
      - zulu-data:/app/data
    restart: unless-stopped

volumes:
  zulu-data:
